import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./auth.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Amazon-Clone',
  description: 'Generated by create next app',
}

export default function AuthRootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white h-screen w-screen min-w-screen min-h-screen'>
        {children}
      </body>
    </html>
  )
}
